RoostCare/Pages/UserManagement/Index.cshtml.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RoostCare.Models.Domain;
using RoostCare.Models.Infrastracture;
using RoostCare.Models.ViewModel.InputModel;

namespace RoostCare.Pages.UserManagement
{
    public class IndexModel : PageModel
    {
        private readonly IBaseRepository<ApplicationUser> _accRepo;
        private readonly UserManager<ApplicationUser> _userManager;
        public IndexModel(
            IBaseRepository<ApplicationUser> accRepo,
            UserManager<ApplicationUser> userManager)
        {
            _accRepo = accRepo;
            _userManager = userManager;
        }
        [BindProperty]
        public UserInputModel InputModel{get; set;}
        public IEnumerable<ApplicationUser> Users { get; set; }
        public async Task OnGetAsync()
        {
            var users = await _accRepo.GetAll();
            Users = users.Where(x => x.UserName != User.Identity?.Name);
        }

        public async Task<IActionResult> OnPostUpdate()
        {
            if (!ModelState.IsValid)
                return BadRequest(ModelState);
            var user = await _userManager.FindByIdAsync(InputModel.Id);
            user.EmailConfirmed = true;
            user.Email = InputModel.Email;
            user.NormalizedEmail = InputModel.Email.ToUpper();
            user.UserName = InputModel.Username;
            user.NormalizedUserName = InputModel.Username.ToUpper();
            user.FirstName = InputModel.FirstName;
            user.MiddleName = InputModel.MiddleName;
            user.LastName = InputModel.LastName;
            user.Sex = InputModel.Sex;
            user.PhoneNumber = InputModel.PhoneNumber;
            user.Address = InputModel.Address;
            await _accRepo.Update(user.Id, user);
            return RedirectToPage();
        }
        public async Task<IActionResult> OnGetDelete(string rId)
        {
            var user = await _accRepo.GetOne(rId);
            await _userManager.UpdateSecurityStampAsync(user);
            await _accRepo.Delete(rId) ;
            TempData["validation-message"] = "Successfully deleted";
            return RedirectToPage();
        }

        public async Task<IActionResult> OnPost()
        {
            if (!ModelState.IsValid)
                return BadRequest(ModelState);
            var user = new ApplicationUser
            {
                EmailConfirmed = true,
                Email = InputModel.Email,
                UserName = InputModel.Username,
                NormalizedEmail = InputModel.Email.ToUpper(),
                NormalizedUserName = InputModel.Username.ToUpper(),
                FirstName = InputModel.FirstName, 
                MiddleName = InputModel.MiddleName,
                LastName = InputModel.LastName,
                Sex = InputModel.Sex,
                PhoneNumber = InputModel.PhoneNumber,
                Address = InputModel.Address
            };
            var result = await _userManager.CreateAsync(user,InputModel.Password);
            if (result.Succeeded)
            {
                await _userManager.AddToRoleAsync(user, "Staff");
            }
            else
            {
                foreach (var error in result.Errors)
                {
                     TempData["validation-message"] = error.Description;
                }
            }
            return RedirectToPage();
        }
    }
}

RoostCare/Pages/UserManagement/Index.cshtml
@page
@using Microsoft.AspNetCore.Identity
@inject UserManager<ApplicationUser> _userManager
@model RoostCare.Pages.UserManagement.IndexModel
@{
}
<h4 class="text-center mb-3 fw-bolder">User Management</h4>
<button data-bs-target="#add-user" data-bs-toggle="modal" class="btn btn-success px-3 mb-2">ADD NEW USER</button>
<partial name="_AddUser" model="new UserInputModel()"/>
<div class="rounded-3 p-2 shadow border border-success border-3" style="background-color:#CEF8D9">
    <div class="overflow-x-scroll">
        <table id="table-data" class="table table-striped table-hover bg-white" style="width:100%">
            <thead>
                <tr>
                    <th>User Name</th>
                    <th>First Name</th>
                    <th>Middle Name</th>
                    <th>Last Name</th>
                    <th>Sex</th>
                    <td>Email</td>
                    <td>Phone Number</td>
                    <td>Address</td>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody class="table-group-divider">
                @foreach (var user in Model.Users)
                {

                    <tr>
                        <td>@user.UserName</td>
                        <td>@user.FirstName</td>
                        <td>@(user.MiddleName ?? "None")</td>
                        <td>@(user.LastName ?? "None")</td>
                        <td>@user.Sex</td>
                        <td>@user.Email</td>
                        <td>@(user.PhoneNumber ?? "None")</td>
                        <td>@(user.Address ?? "None")</td>
                        <td>
                            <div class="d-flex gap-2">
                                <button class="btn btn-success rounded-2" data-bs-toggle="modal" data-bs-target="#update-user-@(user.Id)"><i class="fa fa-pen"></i></button>
                                <partial name="_UpdateUser" model="new UserInputModel{Id = user.Id,Username = user.UserName,FirstName = user.FirstName,MiddleName = user.MiddleName,LastName = user.LastName,Sex = user.Sex,Email = user.Email,PhoneNumber = user.PhoneNumber,Address = user.Address}" />
                                <button data-bs-toggle="modal" data-bs-target="#delete-record-@(user.Id)" class="btn btn-danger"><i class="fa-solid fa-trash-can"></i></button>
                                <partial name="PartialViews/_DeleteModal" model="new DeleteModalViewModel{rId = user.Id}" />
                            </div>

                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    
</div>
@section Scripts {
    <partial name="_ValidationScriptsPartial"></partial>
}

RoostCare/Pages/UserManagement/_AddUser.cshtml
@model UserInputModel
<div class="modal fade" id="add-user">
    <div class="modal-dialog">
        <form method="post">
            <div class="modal-content">
                <div style="background-color: #034007" class="text-white py-3 modal-header">
                    <h5>Add User</h5>
                    <i data-bs-dismiss="modal" class="fa-solid fa-xmark"></i>
                </div>

                <div class="modal-body">
                    <div class="mb-3">
                        <label asp-for="Username" class="mb-2"></label><span class="fw-bolder text-danger">*</span>
                        <input asp-for="Username" class="form-control" placeholder="Enter here.." />
                        <span asp-validation-for="Username" class="text-danger"></span>
                    </div>
                    <div class="mb-3">
                        <label asp-for="Password" class="mb-2"></label><span class="fw-bolder text-danger">*</span>
                        <input asp-for="Password" required class="form-control" placeholder="Enter here.." />
                        <span asp-validation-for="Password" class="text-danger"></span>
                    </div>
                    <div class="mb-3">
                        <label asp-for="ConfirmPassword" class="mb-2"></label><span class="fw-bolder text-danger">*</span>
                        <input asp-for="ConfirmPassword" required class="form-control" placeholder="Enter here.." />
                        <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
                    </div>
                    <div class="mb-3">
                        <label asp-for="FirstName" class="mb-2"></label><span class="fw-bolder text-danger">*</span>
                        <input asp-for="FirstName" class="form-control" placeholder="Enter here.." />
                        <span asp-validation-for="FirstName" class="text-danger"></span>
                    </div>
                    <div class="mb-3">
                        <label asp-for="MiddleName" class="mb-2"></label>
                        <input asp-for="MiddleName" class="form-control" placeholder="Enter here.." />
                        <span asp-validation-for="MiddleName" class="text-danger"></span>
                    </div>
                    <div class="mb-3">
                        <label asp-for="LastName" class="mb-2"></label>
                        <input asp-for="LastName" class="form-control" placeholder="Enter here.." />
                        <span asp-validation-for="LastName" class="text-danger"></span>
                    </div>
                    <div class="mb-3">
                        <label asp-for="Sex" class="mb-2"></label><span class="text-danger fw-bolder"></span>
                        <select asp-for="Sex" asp-items="@Html.GetEnumSelectList<Sex>()" class="form-select" placeholder="Enter here.." ></select>
                        <span asp-validation-for="Sex" class="text-danger"></span>
                    </div>
                    <div class="mb-3">
                        <label asp-for="PhoneNumber" class="mb-2"></label>
                        <input asp-for="PhoneNumber" type="number" class="form-control" placeholder="Enter here.." />
                        <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                    </div>
                    <div class="mb-3">
                        <label asp-for="Email" class="mb-2"></label><span class="fw-bolder text-danger">*</span>
                        <input asp-for="Email" class="form-control" placeholder="Enter here.." />
                        <span asp-validation-for="Email" class="text-danger"></span>
                    </div>
                    <div class="mb-3">
                        <label asp-for="Address" class="mb-2"></label><span class="fw-bolder text-danger">*</span>
                        <input asp-for="Address" class="form-control" placeholder="Enter here.." />
                        <span asp-validation-for="Address" class="text-danger"></span>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="reset" class="btn btn-light">Cancel</button>
                    <button type="submit" class="btn btn-success">Submit</button>
                </div>
            </div>
        </form>

    </div>
</div>

RoostCare/Pages/UserManagement/_UpdateUser.cshtml
@model UserInputModel
<div class="modal fade" id="update-user-@(Model.Id)">
    <div class="modal-dialog">
        <form method="post" asp-page-handler="Update">
            <input type="hidden" asp-for="Id"/>
            <div class="modal-content">
                <div style="background-color: #034007" class="text-white py-3 modal-header">
                    <h5>Update User</h5>
                    <i data-bs-dismiss="modal" class="fa-solid fa-xmark"></i>
                </div>
                <div class="modal-body">
                    <div class="mb-3">
                        <label asp-for="Username" class="mb-2"></label><span class="fw-bolder text-danger">*</span>
                        <input asp-for="Username" class="form-control" placeholder="Enter here.." />
                        <span asp-validation-for="Username" class="text-danger"></span>
                    </div>
                    <div class="mb-3">
                        <label asp-for="FirstName" class="mb-2"></label><span class="fw-bolder text-danger">*</span>
                        <input asp-for="FirstName" class="form-control" placeholder="Enter here.." />
                        <span asp-validation-for="FirstName" class="text-danger"></span>
                    </div>
                    <div class="mb-3">
                        <label asp-for="MiddleName" class="mb-2"></label>
                        <input asp-for="MiddleName" class="form-control" placeholder="Enter here.." />
                        <span asp-validation-for="MiddleName" class="text-danger"></span>
                    </div>
                    <div class="mb-3">
                        <label asp-for="LastName" class="mb-2"></label>
                        <input asp-for="LastName" class="form-control" placeholder="Enter here.." />
                        <span asp-validation-for="LastName" class="text-danger"></span>
                    </div>
                    <div class="mb-3">
                        <label asp-for="Sex" class="mb-2"></label><span class="text-danger fw-bolder">*</span>
                        <select asp-for="Sex" asp-items="@Html.GetEnumSelectList<Sex>()" class="form-select" placeholder="Enter here.."></select>
                        <span asp-validation-for="Sex" class="text-danger"></span>
                    </div>
                    <div class="mb-3">
                        <label asp-for="PhoneNumber" class="mb-2"></label>
                        <input asp-for="PhoneNumber" type="number" class="form-control" placeholder="Enter here.." />
                        <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                    </div>
                    <div class="mb-3">
                        <label asp-for="Email" class="mb-2"></label><span class="fw-bolder text-danger">*</span>
                        <input asp-for="Email" class="form-control" placeholder="Enter here.." />
                        <span asp-validation-for="Email" class="text-danger"></span>
                    </div>
                    <div class="mb-3">
                        <label asp-for="Address" class="mb-2"></label><span class="fw-bolder text-danger">*</span>
                        <input asp-for="Address" class="form-control" placeholder="Enter here.." />
                        <span asp-validation-for="Address" class="text-danger"></span>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="reset" class="btn btn-light">Cancel</button>
                    <button type="submit" class="btn btn-success">Update</button>
                </div>
            </div>
        </form>

    </div>
</div>