RoostCare/Pages/RoosterManagement/AddUpdateMedicationHistory.cshtml.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RoostCare.Models.Domain;
using RoostCare.Models.Infrastracture;
using RoostCare.Models.ViewModel.InputModel;

namespace RoostCare.Pages.RoosterManagement
{
    public class AddUpdateMedicationHistoryModel : BasePageModel<MedicationHistory,MedicationHistoryInputModel>
    {
        private readonly IBaseRepository<MedicationHistory> _medicRepo;
        private readonly IMapper _mapper;
        public AddUpdateMedicationHistoryModel(IBaseRepository<MedicationHistory> repo,IMapper mapper):base(repo,mapper)
        {
            _medicRepo = repo;
            _mapper = mapper;
        }
        public int RoosterId { get; set; }
        public async Task OnGetAsync(int roosterId, int? Id = null)
        {
            RoosterId = roosterId;
            if (Id != null)
            {
                var medicationHistory = await _medicRepo.GetOne(Id.ToString());
                var converted = _mapper.Map<MedicationHistoryInputModel>(medicationHistory);
                Input = converted;
            }
        }
    }
}

RoostCare/Pages/RoosterManagement/AddUpdateRoosterFightHistory.cshtml.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RoostCare.Models.Domain;
using RoostCare.Models.Infrastracture;
using RoostCare.Models.ViewModel.InputModel;

namespace RoostCare.Pages.RoosterManagement
{
    public class AddUpdateRoosterFightHistoryModel : BasePageModel<FightHistory,FightHistoryInputModel>
    {
        private readonly IBaseRepository<FightHistory> _fightRepo;
        private readonly IMapper _mapper;
       public AddUpdateRoosterFightHistoryModel(IBaseRepository<FightHistory> repo,IMapper mapper):base(repo,mapper)
        {
            _fightRepo = repo;
            _mapper = mapper;
        }


        public int RoosterId { get; set; }
        public string? PreviousUrl { get; set; }
        public async Task OnGet(int roosterId,int? Id=null,string? prevUrl = null)
        {
            RoosterId = roosterId;
            if(Id != null)
            {
                var fightHistory = await _fightRepo.GetOne(Id.ToString());
                var converted = _mapper.Map<FightHistoryInputModel>(fightHistory);
                PreviousUrl = prevUrl;
                Input = converted;
            }
        }
    }
}

RoostCare/Pages/RoosterManagement/DeceasedRooster.cshtml.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RoostCare.Models.Domain;
using RoostCare.Models.Infrastracture;
using RoostCare.Models.Services;
using RoostCare.Models.ViewModel;
using RoostCare.Models.ViewModel.InputModel;

namespace RoostCare.Pages.RoosterManagement
{
    public class DeceasedRoosterModel : BasePageModel<Rooster, RoosterInputModel>
    {
        private readonly IRoosterRepository _roosterRepo;
        private readonly FileUploader _fileUploader;
        private readonly IBaseRepository<FightHistory> _fhRepo;
        private readonly IMapper _mapper;
        public DeceasedRoosterModel(
            IRoosterRepository roosterRepo,
            FileUploader fileUploader,
            IMapper mapper,
            IBaseRepository<FightHistory> fhRepo) : base(roosterRepo, mapper)
        {
            _roosterRepo = roosterRepo;
            _fileUploader = fileUploader;
            _mapper = mapper;
            _fhRepo = fhRepo;
        }
        public List<RoosterViewModel> Roosters { get; set; }
        public async Task OnGetAsync()
        {
            var roosters = await _roosterRepo.RoosterRecords();
            var fightHistories = await _fhRepo.GetAll();
            Roosters = roosters
                .GroupBy(x => x.Rooster.Id)
                .Select(f => new RoosterViewModel
                {
                    Rooster = f.First().Rooster,
                    Breed = f.First().Breed,
                    Income = f.First().Income,
                    HasLoose = fightHistories.Where(x => x.RoosterId == f.Key).Any(x => x.FightResult == FightResult.Loss)
                })
                .Where(x => x.HasLoose).ToList();
        }
    }
}

RoostCare/Pages/RoosterManagement/Index.cshtml.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RoostCare.Models.Domain;
using RoostCare.Models.Infrastracture;
using RoostCare.Models.Services;
using RoostCare.Models.ViewModel;
using RoostCare.Models.ViewModel.InputModel;
using System.Security.Cryptography.Xml;

namespace RoostCare.Pages.RoosterManager
{
    [Authorize(Roles = "Admin")]
    public class IndexModel : BasePageModel<Rooster,RoosterInputModel>
    {
        private readonly IRoosterRepository _roosterRepo;
        private readonly FileUploader _fileUploader;
        private readonly IBaseRepository<FightHistory> _fhRepo;
        private readonly IMapper _mapper;
        public IndexModel(
            IRoosterRepository roosterRepo,
            FileUploader fileUploader,
            IMapper mapper,
            IBaseRepository<FightHistory> fhRepo) : base(roosterRepo, mapper)
        {
            _roosterRepo = roosterRepo;
            _fileUploader = fileUploader;
            _mapper = mapper;
            _fhRepo = fhRepo;
        }
        public List<RoosterViewModel> Roosters { get; set; }
        public async Task OnGetAsync()
        {
            var roosters = await _roosterRepo.RoosterRecords();
            var fightHistories = await _fhRepo.GetAll();
            Roosters = roosters
                .GroupBy(x => x.Rooster.Id)
                .Select(f => new RoosterViewModel
                {
                    Rooster = f.First().Rooster,
                    Breed = f.First().Breed,
                    Income = f.First().Income,
                    HasLoose = fightHistories.Where(x => x.RoosterId == f.Key).Any(x => x.FightResult == FightResult.Loss)
                })
                .Where(x => x.Income == null && !x.HasLoose).ToList();

        }
        public async Task<IActionResult>OnPostAddRooster()
        {
            if (!ModelState.IsValid)
                return BadRequest(ModelState);
            var converted = _mapper.Map<Rooster>(Input);
            converted.RoosterImageFileName = await _fileUploader.UploadFile(Input.RImageFile, "RProfile");
            await _roosterRepo.Add(converted);
            return RedirectToPage();
        }
        public async Task<IActionResult> OnPostUpdateRooster()
        {
            if (!ModelState.IsValid)
                return BadRequest(ModelState);
            var converted = _mapper.Map<Rooster>(Input);
            var rooster = await _roosterRepo.GetOne(Input.Id.ToString());
            converted.RoosterImageFileName = await _fileUploader.UploadFile(Input.RImageFile, "RProfile")??rooster.RoosterImageFileName;
            await _roosterRepo.Update(converted.Id.ToString(), converted);
            return RedirectToPage();
        }
        
    }
}

RoostCare/Pages/RoosterManagement/RoosterSoldOut.cshtml.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RoostCare.Models.Domain;
using RoostCare.Models.Infrastracture;
using RoostCare.Models.Services;
using RoostCare.Models.ViewModel.InputModel;
using RoostCare.Models.ViewModel;

namespace RoostCare.Pages.RoosterManagement
{
	[Authorize(Roles = "Admin")]
	public class RoosterSoldOutModel : BasePageModel<Rooster, RoosterInputModel>
	{
		private readonly IRoosterRepository _roosterRepo;
		private readonly FileUploader _fileUploader;
		private readonly IMapper _mapper;
		public RoosterSoldOutModel(
			IRoosterRepository roosterRepo,
			FileUploader fileUploader,
			IMapper mapper) : base(roosterRepo, mapper)
		{
			_roosterRepo = roosterRepo;
			_fileUploader = fileUploader;
			_mapper = mapper;
		}
		public List<RoosterViewModel> Roosters { get; set; }
		public async Task OnGetAsync()
		{
			var roosters = await _roosterRepo.RoosterRecords();
			Roosters = roosters
				.GroupBy(x => x.Rooster.Id)
				.Select(f => new RoosterViewModel
				{
					Rooster = f.First().Rooster,
					Breed = f.First().Breed,
					Income = f.First().Income
				})
				.Where(x => x.Income != null && x.Rooster.RoosterCategory == RoosterCategory.ForSale)
				.ToList();
		}
	}
	
}

RoostCare/Pages/RoosterManagement/ViewRoosterInformation.cshtml.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.SignalR;
using RoostCare.Hubs;
using RoostCare.Models.Domain;
using RoostCare.Models.Infrastracture;
using RoostCare.Models.ViewModel;
using RoostCare.Models.ViewModel.InputModel;
using System.Net;
using System.Runtime.CompilerServices;

namespace RoostCare.Pages.RoosterManagement
{
	[ValidateAntiForgeryToken]
	[Authorize]
	public class ViewRoosterInformationModel : PageModel
	{
		private readonly IRoosterRepository _roosterRepo;
		private readonly IBaseRepository<FightHistory> _fHRepo;
		private readonly IBaseRepository<MedicationHistory> _medicRepo;

		private readonly IBaseRepository<ApplicationUser> _accRepo;
		private readonly UserManager<ApplicationUser> _userManager;

		private readonly IBaseRepository<NotificationEntity> _notifRepo;
		private readonly IMapper _mapper;
		private readonly IHubContext<NotificationHub,INotificationHub> _notifHub;
		public ViewRoosterInformationModel(
			IRoosterRepository roosterRepo,
			 IBaseRepository<FightHistory> fHRepo,
			 IBaseRepository<MedicationHistory> medicRepo,
			 IBaseRepository<NotificationEntity> notifRepo,
			  IBaseRepository<ApplicationUser> accRepo,
			  UserManager<ApplicationUser> userManager,
			  IHubContext<NotificationHub, INotificationHub> notifHub,
		IMapper mapper)
		{
			_roosterRepo = roosterRepo;
			_fHRepo = fHRepo;
			_medicRepo = medicRepo;
			_notifRepo = notifRepo;
			_mapper = mapper;
			_userManager = userManager;
			_notifHub = notifHub;

		}
		public RoosterViewModel Rooster { get; set; }
		public IEnumerable<FightHistory> FightHistories { get; set; }
		public IEnumerable<MedicationHistory> MedicationHistories { get; set; }
		public string? PreviousUrl { get; set; }

		[BindProperty]
		public RoosterStatus? RStatInput { get; set; }

		[BindProperty]
		public FightHistoryInputModel FInputModel { get; set; }
		[BindProperty]
		public MedicationHistoryInputModel MInputModel { get; set; }
		public async Task OnGetAsync(int Id, string? prevUrl = null)
		{
			var fightHistories = await _fHRepo.GetAll();
			PreviousUrl = prevUrl;
			FightHistories = fightHistories.Where(x => x.RoosterId == Id).ToList();
			var medicHistories = await _medicRepo.GetAll();
			MedicationHistories = medicHistories.Where(x => x.RoosterId == Id).ToList();
			var roosters = await _roosterRepo.RoosterRecords();
			Rooster = roosters.FirstOrDefault(x => x.Rooster.Id == Id);
		}

		public async Task<IActionResult> OnGetDeleteFightHistory(string rId, int Id)
		{
			await _fHRepo.Delete(rId);
			TempData["validation-message"] = "Successfully deleted";
			return RedirectToPage("ViewRoosterInformation", new { Id });
		}
		public async Task<IActionResult> OnGetDeleteMedicationHistory(string rId, int Id)
		{
			await _medicRepo.Delete(rId);
			TempData["validation-message"] = "Successfully deleted";
			return RedirectToPage("ViewRoosterInformation", new { Id });
		}


		public async Task<IActionResult> OnPostAddFight(string prevUrl)
		{

			var converted = _mapper.Map<FightHistory>(FInputModel);
			await _fHRepo.Add(converted);
			var Id = converted.RoosterId;
			TempData["validation-message"] = "Successfully added";
			return RedirectToPage("ViewRoosterInformation", new { Id, prevUrl });

		}
		public async Task<IActionResult> OnPostAddMedication(string prevUrl)
		{
			var converted = _mapper.Map<MedicationHistory>(MInputModel);
			await _medicRepo.Add(converted);
			var Id = converted.RoosterId;
			TempData["validation-message"] = "Successfully added";
			return RedirectToPage("ViewRoosterInformation", new { Id, prevUrl });

		}
		public async Task<IActionResult> OnPostUpdateFight(string prevUrl)
		{
			var converted = _mapper.Map<FightHistory>(FInputModel);
			await _fHRepo.Update(converted.Id.ToString(), converted);
			var Id = converted.RoosterId;
			TempData["validation-message"] = "Successfully updated";
			return RedirectToPage("ViewRoosterInformation", new { Id, prevUrl });

		}
		public async Task<IActionResult> OnPostUpdateMedication(string prevUrl)
		{
			var converted = _mapper.Map<MedicationHistory>(MInputModel);
			await _medicRepo.Update(converted.Id.ToString(), converted);
			var Id = converted.RoosterId;
			TempData["validation-message"] = "Successfully updated";
			return RedirectToPage("ViewRoosterInformation", new { Id, prevUrl });

		}

		public async Task<IActionResult> OnPostUpdateRStatus(string rId, string prevUrl)
		{
			var rooster = await _roosterRepo.GetOne(rId);
			if (rooster == null)
				return BadRequest($"{rId} is invalid id");

			rooster.RoosterStatus = (RoosterStatus)RStatInput;

			var users = await _userManager.GetUsersInRoleAsync("Staff");
			var notifications = await _notifRepo.GetAll();
			var rStatus = rooster.RoosterStatus == RoosterStatus.ReadyToFight ? "is already ready for the new fight." : rooster.RoosterStatus == RoosterStatus.UnderMaintenance ? "has some minor or major injury" : rooster.RoosterStatus == RoosterStatus.Healthy ? "is healthy" : "is injured and need medication";
			
				foreach (var user in users)
				{
					var notifCount = notifications.Where(x => !x.IsViewed && x.Recipient == user.Id).Count();
					var notifCountString = notifCount > 5 ? $"5+" : notifCount.ToString();
					NotificationEntity notifVal = new NotificationEntity();
					notifVal.Title = "Rooster Status";
					notifVal.Description = $"The status of the rooster with ID {rooster.Id.ToString("00000")} {rStatus}";
					notifVal.IsViewed = false;
					notifVal.Recipient = user.Id;
					notifVal.IsArchived = false;
					notifVal.UpdatedAt = DateTime.Now;
					notifVal.AddedAt = DateTime.Now;
					await _notifRepo.Add(notifVal);
					_notifHub.Clients.User(user.Id).NotificationAlert(notifCountString);
				}
			await _roosterRepo.Update(rId, rooster);
			TempData["validation-message"] = "Successfully updated";
			var Id = rooster.Id;
			return RedirectToPage("ViewRoosterInformation", new { Id, prevUrl });
		}
	}
}

RoostCare/Pages/RoosterManagement/AddUpdateMedicationHistory.cshtml
@page
@model RoostCare.Pages.RoosterManagement.AddUpdateMedicationHistoryModel
@{
}
<div class="d-flex align-items-center justify-content-center" style="height: 50vh">
    @if (Model.Input == null)
    {
        <form method="post" asp-route-returnUrl="@("./ViewRoosterInformation")" asp-route-Id="@Model.RoosterId">
            <input asp-for="Input.RoosterId" value="@Model.RoosterId" type="hidden" />
            <div class="bg-white rounded-3 overflow-hidden shadow" style="width: 400px">
                <h5 class="theme-bg-green text-center text-white mb-4 py-2">Fill up</h5>
                <div class="p-3">
                    <div class="mb-3">
                        <label asp-for="Input.DateAdministered" class="mb-2 fw-bold">Date Administered<span class="text-danger">*</span></label>
                        <input class="form-select border border-success" asp-for="Input.DateAdministered" />
                        <span asp-validation-for="Input.DateAdministered" class="text-danger"></span>
                    </div>
                    <div class="mb-3">
                        <label asp-for="Input.Vitamin" class="mb-2 fw-bold">Vitamin</label>
                        <input class="form-control border border-success" asp-for="Input.Vitamin" />
                        <span asp-validation-for="Input.Vitamin"></span>
                    </div>
                    <div class="d-flex justify-content-end gap-2">
                        <a asp-page="./ViewRoosterInformation" asp-route-Id="@Model.RoosterId" class="btn btn-light">Cancel</a>
                        <button type="submit" class="btn theme-bg-green text-white">Submit</button>
                    </div>
                </div>

            </div>
        </form>
    }
    else
    {
        <form method="post" asp-page-handler="Update" asp-route-returnUrl="@("./ViewRoosterInformation")" asp-route-Id="@Model.RoosterId">
            <input asp-for="Input.RoosterId" value="@Model.RoosterId" type="hidden" />
            <input asp-for="Input.AddedAt" type="hidden"/>
            <div class="bg-white rounded-3 overflow-hidden shadow" style="width: 400px">
                <h5 class="theme-bg-green text-center text-white mb-4 py-2">Fill up</h5>
                <div class="p-3">
                    <input asp-for="Input.Id" class="form-control text-center" readonly />
                    <div class="mb-3">
                        <label asp-for="Input.DateAdministered" class="mb-2 fw-bold">Date Administered<span class="text-danger">*</span></label>
                        <input class="form-select border border-success" asp-for="Input.DateAdministered" />
                        <span asp-validation-for="Input.DateAdministered" class="text-danger"></span>
                    </div>
                    <div class="mb-3">
                        <label asp-for="Input.Vitamin" class="mb-2 fw-bold">Vitamin</label>
                        <input class="form-control border border-success" asp-for="Input.Vitamin" />
                        <span asp-validation-for="Input.Vitamin"></span>
                    </div>
                    <div class="d-flex justify-content-end gap-2">
                        <a asp-page="./ViewRoosterInformation" asp-route-Id="@Model.RoosterId" class="btn btn-light">Cancel</a>
                        <button type="submit" class="btn theme-bg-green text-white">Submit</button>
                    </div>
                </div>

            </div>
        </form>
    }

</div>
@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

RoostCare/Pages/RoosterManagement/AddUpdateRoosterFightHistory.cshtml
@page
@model RoostCare.Pages.RoosterManagement.AddUpdateRoosterFightHistoryModel
@{

}
<div class="d-flex align-items-center justify-content-center" style="height: 50vh">
    @if(Model.Input == null)
    {
        <form method="post" asp-route-returnUrl="@(Model.PreviousUrl)" asp-route-Id="@Model.RoosterId">
            <input asp-for="Input.RoosterId" value="@Model.RoosterId" type="hidden" />
            <div class="bg-white rounded-3 overflow-hidden shadow" style="width: 400px">
                <h5 class="theme-bg-green text-center text-white mb-4 py-2">Fill up</h5>
                <div class="p-3">
                    <div class="mb-3">
                        <label asp-for="Input.FightResult" class="mb-2 fw-bold">Fight Result<span class="text-danger">*</span></label>
                        <select class="form-select border border-success" asp-for="Input.FightResult" asp-items="@Html.GetEnumSelectList<FightResult>()"></select>
                        <span asp-validation-for="Input.FightResult"></span>
                    </div>
                    <div class="mb-3">
                        <label asp-for="Input.RoosterInjury" class="mb-2 fw-bold">Rooster Injury<span class="text-danger">*</span></label>
                        <select class="form-select border border-success" asp-for="Input.RoosterInjury" asp-items="@Html.GetEnumSelectList<RoosterInjury>()"></select>
                        <span asp-validation-for="Input.RoosterInjury"></span>
                    </div>
                    <div class="mb-3">
                        <label asp-for="Input.DateOfFight" class="mb-2 fw-bold">Date Of the fight</label>
                        <input class="form-control border border-success" asp-for="Input.DateOfFight" />
                        <span asp-validation-for="Input.DateOfFight"></span>
                    </div>
                    <div class="d-flex justify-content-end gap-2">
                        <a asp-page="./ViewRoosterInformation" asp-route-prevUrl="@Model.PreviousUrl" asp-route-Id="@Model.RoosterId" class="btn btn-light">Cancel</a>
                        <button type="submit" class="btn theme-bg-green text-white">Submit</button>
                    </div>
                </div>

            </div>
        </form>
    }
    else
    {
        <form method="post" asp-page-handler="Update" asp-route-returnUrl="@(Model.PreviousUrl)" asp-route-Id="@Model.RoosterId">
            <input asp-for="Input.RoosterId" value="@Model.RoosterId" type="hidden" />
            <input asp-for="Input.AddedAt" type="hidden" />
            <div class="bg-white rounded-3 overflow-hidden shadow" style="width: 400px">
                <h5 class="theme-bg-green text-center text-white mb-4 py-2">Fill up</h5>
                <div class="p-3">

                    <input asp-for="Input.Id" class="form-control text-center" readonly />
                    <div class="mb-3">
                        <label asp-for="Input.FightResult" class="mb-2 fw-bold">Fight Result<span class="text-danger">*</span></label>
                        <select class="form-select border border-success" asp-for="Input.FightResult" asp-items="@Html.GetEnumSelectList<FightResult>()"></select>
                        <span asp-validation-for="Input.FightResult"></span>
                    </div>
                    <div class="mb-3">
                        <label asp-for="Input.RoosterInjury" class="mb-2 fw-bold">Rooster Injury<span class="text-danger">*</span></label>
                        <select class="form-select border border-success" asp-for="Input.RoosterInjury" asp-items="@Html.GetEnumSelectList<RoosterInjury>()"></select>
                        <span asp-validation-for="Input.RoosterInjury"></span>
                    </div>
                    <div class="mb-3">
                        <label asp-for="Input.DateOfFight" class="mb-2 fw-bold">Date Of the fight</label>
                        <input class="form-control border border-success" asp-for="Input.DateOfFight" />
                        <span asp-validation-for="Input.DateOfFight"></span>
                    </div>
                    <div class="d-flex justify-content-end gap-2">
                        <a asp-page="./ViewRoosterInformation" asp-route-prevUrl="@Model.PreviousUrl" asp-route-Id="@Model.RoosterId" asp-route-Id="@Model.RoosterId" class="btn btn-light">Cancel</a>
                        <button type="submit" class="btn theme-bg-green text-white">Update</button>
                    </div>
                </div>

            </div>
        </form>
    }
   
</div>
@section Scripts{
    <partial name="_ValidationScriptsPartial"/>
}

RoostCare/Pages/RoosterManagement/DeceasedRooster.cshtml
@page
@model RoostCare.Pages.RoosterManagement.DeceasedRoosterModel
@{
}
<div class="mb-4">
    <h4 class="m-0">Rooster Management</h4>
    <a asp-page="./Index">Rooster List /</a> <span class="text-body-tertiary">Deceased</span>
</div>
<h4 class="text-center mb-3 fw-bolder">Deceased Rooster</h4>
<div class="rounded-3 p-2 shadow border border-success border-3" style="background-color:#CEF8D9">
    <div class="overflow-x-scroll">
        <table id="table-data" class="table table-striped table-hover bg-white" style="width:100%">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Rooster Profile Picture</th>
                    <th>Breed</th>
                    <th>Category</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody class="table-group-divider">
                @foreach (var rooster in Model.Roosters)
                {
                    <tr>
                        <td>@rooster.Rooster.Id.ToString("00000")</td>
                        <td>
                            <div class="d-flex justify-content-center align-items-center">
                                <img src="~/RProfile/@rooster.Rooster.RoosterImageFileName" width="70" height="70" class="rounded-circle" />
                            </div>
                        </td>
                        <td>@rooster.Breed.BreedName</td>
                        <td>@rooster.Rooster.RoosterCategory</td>

                        <td class="text-nowrap">
                            <a class="btn btn-warning text-white rounded-3" asp-page="./ViewRoosterInformation" asp-route-Id="@rooster.Rooster.Id"><i class="fa-solid fa-eye"></i></a>
                            <button data-bs-toggle="modal" data-bs-target="#delete-record-@(rooster.Rooster.Id)" class="btn btn-danger"><i class="fa-solid fa-trash-can"></i></button>
                            <partial name="PartialViews/_DeleteModal" model="new DeleteModalViewModel(){rId = rooster.Rooster.Id.ToString()}" />
                        </td>
                    </tr>
                }
            </tbody>

        </table>
    </div>

</div>

RoostCare/Pages/RoosterManagement/_AddFightHistory.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

RoostCare/Pages/RoosterManagement/_AddRooster.cshtml
@model RoosterInputModel
@inject IBaseRepository<Breed> _breedRepo;
@{
    var roosters = await _breedRepo.GetAll();
}
<div class="modal fade" id="add-rooster">
    <div class="modal-dialog">
        <form method="post" enctype="multipart/form-data" asp-page-handler="AddRooster">
            @Html.AntiForgeryToken()
            <div class="modal-content">
                <div style="background-color: #034007" class="text-white py-3 modal-header">
                    <h5>Add Rooster</h5>
                    <i data-bs-dismiss="modal" class="fa-solid fa-xmark"></i>
                </div>
                <div class="modal-body">
                    <div class="mb-3">
                        <label asp-for="BreedId" class="mb-2"></label><span class="text-danger fw-bolder"></span>
                        <select asp-for="BreedId" asp-items="@roosters.Select(x => new SelectListItem(x.BreedName,x.Id.ToString()))" class="form-select" style="border-color: #034007">
                            <option value="" hidden disabled selected>Select..</option>
                        </select>
                        <span asp-validation-for="BreedId" class="text-danger"></span>
                    </div>
                    <div class="mb-3">
                        <label asp-for="RoosterCategory" class="mb-2"></label><span class="text-danger fw-bolder"></span>
                        <select id="rooster-category-input" asp-for="RoosterCategory" asp-items="@Html.GetEnumSelectList<RoosterCategory>()" class="form-select" style="border-color: #034007">
                            <option value="" hidden disabled selected></option>
                        </select>
                        <span asp-validation-for="RoosterCategory" class="text-danger"></span>
                    </div>
                    <div class="mb-3" id="price-input">
                        <label asp-for="Price" class="mb-2"></label>
                        <input asp-for="Price" class="form-control" style="border-color: #034007" placeholder="Enter here.." />
                        <span asp-validation-for="Price" class="text-danger"></span>
                    </div>
                    <div class="mb-3">
                        <label asp-for="RoosterStatus"></label>
                        <select class="form-select" style="border-color: #034007" asp-items="@Html.GetEnumSelectList<RoosterStatus>()" asp-for="RoosterStatus"></select>
                        <span asp-validation-for="RoosterStatus" class="text-danger"></span>
                    </div>
                    <div class="mb-3">
                        <label asp-for="RImageFile" class="mb-2"></label>
                        <input asp-for="RImageFile" class="form-control" accept="image/*" style="border-color: #034007" placeholder="Enter here.." />
                        <span asp-validation-for="RImageFile" class="text-danger"></span>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="reset" class="btn btn-light">Cancel</button>
                    <button type="submit" class="btn btn-success">Submit</button>
                </div>
            </div>
        </form>
       
    </div>
</div>